/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health_check": {
    /** Get Health Check */
    get: operations["get_health_check_health_check_get"];
  };
  "/hello_world": {
    /** Get Hello World */
    get: operations["get_hello_world_hello_world_get"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Health Check */
  get_health_check_health_check_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** Get Hello World */
  get_hello_world_hello_world_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
}
