version: '3.8'
services:
  # this is the container that vscode will use as the coding environment
  dev:
    build:
      context: .
    tty: true

    volumes:
      - ../..:/workspaces:cached
      # NOTE: AWS CLI looks for authentication tokens at this location
      # so mapping it from localhost:
      - ../.aws:/home/vscode/.aws

    # prevents things from shutting down after the process ends.
    command: sleep infinity

    # Note: env vars defined in the .env file must not overlap
    # with the variables defined environment section
    env_file:
      - ../.env
